// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvOZrAu_9duIn5iTf1-yt1W94pmL5vjs',
    appId: '1:125149603567:web:4550fc490665e6601d1d1a',
    messagingSenderId: '125149603567',
    projectId: 'musicapp-f579a',
    authDomain: 'musicapp-f579a.firebaseapp.com',
    storageBucket: 'musicapp-f579a.firebasestorage.app',
    measurementId: 'G-HLCTJS1XPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8TmJ_xx6ortWTyUCG1K9xcG6YGHKFZa4',
    appId: '1:125149603567:android:446cefd652faa2741d1d1a',
    messagingSenderId: '125149603567',
    projectId: 'musicapp-f579a',
    storageBucket: 'musicapp-f579a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB65By_96USrlcV-8rsWNUNutOQb5O58vU',
    appId: '1:125149603567:ios:9e691a36340b4c9c1d1d1a',
    messagingSenderId: '125149603567',
    projectId: 'musicapp-f579a',
    storageBucket: 'musicapp-f579a.firebasestorage.app',
    iosClientId: '125149603567-qe26gaid3ia7obf88i9rjv7mqicl98e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB65By_96USrlcV-8rsWNUNutOQb5O58vU',
    appId: '1:125149603567:ios:9e691a36340b4c9c1d1d1a',
    messagingSenderId: '125149603567',
    projectId: 'musicapp-f579a',
    storageBucket: 'musicapp-f579a.firebasestorage.app',
    iosClientId: '125149603567-qe26gaid3ia7obf88i9rjv7mqicl98e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyvOZrAu_9duIn5iTf1-yt1W94pmL5vjs',
    appId: '1:125149603567:web:a914449c5a9593ac1d1d1a',
    messagingSenderId: '125149603567',
    projectId: 'musicapp-f579a',
    authDomain: 'musicapp-f579a.firebaseapp.com',
    storageBucket: 'musicapp-f579a.firebasestorage.app',
    measurementId: 'G-50BM6MBKRL',
  );
}
